title: "markkhn's Blog"
email: markkhn@sjtu.edu.cn
description: >-
  电子工程 | AI | Coding | 现代极简博客
baseurl: ""
url: "https://markkhn.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
locale: zh-CN
logo: /assets/images/Profile_photo.png

# 作者信息
author:
  name: markkhn
  avatar: /assets/images/Profile_photo.png
  bio: Eletronic Engineering Student | AI and Coding Enthusiast
  location: Shanghai Jiao Tong University
  email: markkhn@sjtu.edu.cn

# 导航栏
header_pages:
  - index.md
  - _pages/archive.md
  - _pages/tags.md

# 极简风格设置
minimal_mistakes_skin: "air"

# 博客设置
paginate: 5
paginate_path: "/page:num/"
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# 归档和标签
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true 